import Foundation

/// Kubernetes port-forward window: connections, service browser, settings.
enum KubernetesStrings {
    static let entries: [String: (en: String, zh: String)] = [
        "k8s.connection": (en: "Connection", zh: "连接"),
        "k8s.connections": (en: "Connections", zh: "连接"),
        "k8s.import": (en: "Import", zh: "导入"),
        "k8s.importFromKubernetes": (en: "Import from Kubernetes", zh: "从 Kubernetes 导入"),
        "k8s.addConnection": (en: "Add Connection", zh: "添加连接"),
        "k8s.addConnectionHelp": (en: "Add Connection", zh: "添加连接"),
        "k8s.noConnections": (en: "No connections configured", zh: "未配置连接"),
        "k8s.noConnectionsTitle": (en: "No Connections", zh: "无连接"),
        "k8s.noConnectionsMatch": (en: "No connections match '%@'", zh: "没有匹配「%@」的连接"),
        "k8s.connectedCount": (en: "%ld of %ld connected", zh: "%ld / %ld 已连接"),
        "k8s.killing": (en: "Killing processes...", zh: "正在结束进程…"),
        "k8s.killAllStuck": (en: "Kill All Stuck", zh: "结束全部卡住进程"),
        "k8s.startAll": (en: "Start All", zh: "全部启动"),
        "k8s.stopAll": (en: "Stop All", zh: "全部停止"),
        "k8s.forceStop": (en: "Force Stop", zh: "强制停止"),
        "k8s.forceStopHelp": (en: "Kill all stuck kubectl/socat processes", zh: "结束所有卡住的 kubectl/socat 进程"),
        "k8s.searchPlaceholder": (en: "Search...", zh: "搜索…"),
        "k8s.selectConnection": (en: "Select a connection", zh: "选择连接"),
        "k8s.selectConnectionDetail": (en: "Click on a connection to view details and logs", zh: "点击连接以查看详情和日志"),
        "k8s.addOrImport": (en: "Add a connection or import from Kubernetes", zh: "添加连接或从 Kubernetes 导入"),
        "k8s.configuration": (en: "Configuration", zh: "配置"),
        "k8s.connectionName": (en: "Connection name", zh: "连接名称"),
        "k8s.name": (en: "Name", zh: "名称"),
        "k8s.namespace": (en: "Namespace", zh: "命名空间"),
        "k8s.namespaces": (en: "Namespaces", zh: "命名空间"),
        "k8s.noNamespaces": (en: "No namespaces", zh: "没有命名空间"),
        "k8s.addCustomNamespace": (en: "Add Custom Namespace", zh: "添加自定义命名空间"),
        "k8s.addCustomNamespaceHelp": (en: "Add custom namespace", zh: "添加自定义命名空间"),
        "k8s.refreshNamespacesHelp": (en: "Refresh namespaces", zh: "刷新命名空间"),
        "k8s.enterNamespaces": (en: "Enter namespace names (comma-separated for multiple)", zh: "输入命名空间名称（多个用逗号分隔）"),
        "k8s.namespacePlaceholder": (en: "e.g., production, staging, dev", zh: "例如：production, staging, dev"),
        "k8s.addCustom": (en: "Add Custom", zh: "添加自定义"),
        "k8s.service": (en: "Service", zh: "服务"),
        "k8s.services": (en: "Services", zh: "服务"),
        "k8s.serviceDetails": (en: "Service Details", zh: "服务详情"),
        "k8s.noServices": (en: "No services found", zh: "未找到服务"),
        "k8s.loadingServices": (en: "Loading services...", zh: "正在加载服务…"),
        "k8s.selectNamespace": (en: "Select a namespace", zh: "选择命名空间"),
        "k8s.selectService": (en: "Select a service", zh: "选择服务"),
        "k8s.selectPort": (en: "Select Port", zh: "选择端口"),
        "k8s.noPortsDefined": (en: "No ports defined", zh: "未定义端口"),
        "k8s.port": (en: "Port", zh: "端口"),
        "k8s.ports": (en: "Ports", zh: "端口"),
        "k8s.portConfiguration": (en: "Port Configuration", zh: "端口配置"),
        "k8s.portMapping": (en: "Port Mapping", zh: "端口映射"),
        "k8s.portPlaceholder": (en: "port", zh: "端口"),
        "k8s.status": (en: "Status", zh: "状态"),
        "k8s.logs": (en: "Logs", zh: "日志"),
        "k8s.noLogs": (en: "No logs yet", zh: "暂无日志"),
        "k8s.clearLogs": (en: "Clear Logs", zh: "清空日志"),
        "k8s.copyAllLogs": (en: "Copy All Logs (Markdown)", zh: "复制全部日志（Markdown）"),
        "k8s.proxy": (en: "Proxy", zh: "代理"),
        "k8s.local": (en: "Local", zh: "本地"),
        "k8s.remote": (en: "Remote", zh: "远程"),
        "k8s.localPort": (en: "Local port:", zh: "本地端口："),
        "k8s.proxyPort": (en: "Proxy port:", zh: "代理端口："),
        "k8s.connectTo": (en: "Connect to:", zh: "连接到："),
        "k8s.localPortValue": (en: "Local: %ld", zh: "本地：%ld"),
        "k8s.proxyValue": (en: "Proxy: %ld", zh: "代理：%ld"),
        "k8s.connectToValue": (en: "Connect to: localhost:%ld", zh: "连接到：localhost:%ld"),
        "k8s.enableProxy": (en: "Enable Proxy (socat)", zh: "启用代理（socat）"),
        "k8s.options": (en: "Options", zh: "选项"),
        "k8s.multiConn": (en: "Multi-conn", zh: "多连接"),
        "k8s.multiConnHelp": (en: "Multiple simultaneous connections", zh: "多个同时连接"),
        "k8s.enableMultipleHelp": (en: "Enable multiple simultaneous connections", zh: "启用多个同时连接"),
        "k8s.autoReconnect": (en: "Auto Reconnect", zh: "自动重连"),
        "k8s.notifyOnConnect": (en: "Notify on Connect", zh: "连接时通知"),
        "k8s.notifyOnDisconnect": (en: "Notify on Disconnect", zh: "断开时通知"),
        "k8s.onConnect": (en: "On Connect", zh: "连接时"),
        "k8s.onDisconnect": (en: "On Disconnect", zh: "断开时"),
        "k8s.showNotificationsHelp": (en: "Show connection notifications", zh: "显示连接通知"),
        "k8s.startup": (en: "Startup", zh: "启动"),
        "k8s.autoStartConnections": (en: "Auto-start connections on app launch", zh: "应用启动时自动启动连接"),
        "k8s.dependencies": (en: "Dependencies", zh: "依赖"),
        "k8s.installed": (en: "Installed", zh: "已安装"),
        "k8s.optional": (en: "(optional)", zh: "（可选）"),
        "k8s.custom": (en: "(custom)", zh: "（自定义）"),
        "k8s.auto": (en: "(auto)", zh: "（自动）"),
        "k8s.browse": (en: "Browse...", zh: "浏览…"),
        "k8s.reset": (en: "Reset", zh: "重置"),
        "k8s.kubectlRequired": (en: "kubectl is required", zh: "需要 kubectl"),
        "k8s.searchableNoItems": (en: "No items", zh: "无项目"),
        "k8s.searchableNoMatches": (en: "No matches", zh: "无匹配"),
        "k8s.serviceTypePorts": (en: "%@ · %ld port(s)", zh: "%@ · %ld 个端口"),
        "k8s.portCount": (en: "%ld port(s)", zh: "%ld 个端口"),
        "k8s.serviceBrowser": (en: "Kubernetes Service Browser", zh: "Kubernetes 服务浏览器"),
        "k8s.startBrowsing": (en: "Start Browsing", zh: "开始浏览"),
        "k8s.browseDescription": (en: "Browse your Kubernetes cluster to find services and create port-forward connections.", zh: "浏览你的 Kubernetes 集群，查找服务并创建端口转发连接。"),
        "k8s.selectExecutable": (en: "Select %@ executable", zh: "选择 %@ 可执行文件"),
        "k8s.newConnection": (en: "New Connection", zh: "新建连接"),
        "k8s.showFlatList": (en: "Show flat list", zh: "显示平铺列表"),
        "k8s.groupByNamespace": (en: "Group by namespace", zh: "按命名空间分组"),
        "k8s.searchNamespaces": (en: "Search namespaces...", zh: "搜索命名空间…"),
        "k8s.searchServices": (en: "Search services...", zh: "搜索服务…"),
        "k8s.missingDependencies": (en: "Missing Dependencies", zh: "缺少依赖"),
        "k8s.kubectlRequiredForForwarding": (en: "kubectl is required for port forwarding", zh: "端口转发需要 kubectl"),
        "k8s.failedToRunBrew": (en: "Failed to run brew", zh: "运行 brew 失败"),
        "k8s.failedToLaunchBrew": (en: "Failed to launch brew", zh: "启动 brew 失败"),
        "k8s.installationFailed": (en: "Installation failed: %@", zh: "安装失败：%@"),
        "k8s.localhostPort": (en: "localhost:%ld", zh: "localhost:%ld"),
        "k8s.homebrewMissing": (en: "Homebrew is not installed. Please install it from https://brew.sh", zh: "未安装 Homebrew。请从 https://brew.sh 安装"),
        "k8s.depInstalled": (en: "%@: Installed", zh: "%@：已安装"),
        "k8s.depFailed": (en: "%@: Failed - %@", zh: "%@：失败 - %@"),
        "k8s.error.portForwardFailed": (en: "Port forward failed to start", zh: "端口转发启动失败"),
        "k8s.error.directExecFailed": (en: "Direct exec proxy failed to start", zh: "直接执行代理启动失败"),
        "k8s.error.socatFailed": (en: "Socat proxy failed to start", zh: "Socat 代理启动失败"),
        "k8s.error.kubectlPortForward": (en: "kubectl port-forward error on port %ld", zh: "端口 %ld 的 kubectl port-forward 出错"),
        "k8s.error.processTerminated": (en: "Process terminated", zh: "进程已终止"),
        "k8s.error.connectionLost": (en: "Connection lost", zh: "连接已断开"),
        "k8s.error.proxyConnectionLost": (en: "Proxy connection lost", zh: "代理连接已断开"),
        "k8s.error.proxyError": (en: "Proxy error on port %ld", zh: "端口 %ld 的代理出错"),
        "k8s.error.proxyTerminated": (en: "Proxy terminated", zh: "代理已终止"),
        "k8s.error.processTerminatedUnexpectedly": (en: "Process terminated unexpectedly", zh: "进程意外终止"),
        "k8s.error.tunnelManagedElsewhere": (en: "Tunnel is managed elsewhere (active edge connections from other origins).", zh: "隧道由其他来源管理（存在来自其他来源的活动边缘连接）。"),
        "k8s.error.cloudflaredExitedUnexpectedly": (en: "cloudflared exited unexpectedly", zh: "cloudflared 意外退出"),
        "k8s.error.cloudflaredExitedWithStatus": (en: "cloudflared exited with status %ld", zh: "cloudflared 退出，状态码 %ld"),
        "k8s.error.socatNotFound": (en: "socat not found", zh: "未找到 socat"),
        "k8s.error.socatNotFoundMulti": (en: "socat not found for multi-connection mode", zh: "多连接模式未找到 socat"),
        "k8s.log.portInUseRecovering": (en: "Port %ld in use, auto-recovering...", zh: "端口 %ld 被占用，正在自动恢复…"),
        "k8s.log.retrying": (en: "Retrying connection...", zh: "正在重试连接…"),
    ]
}
