import Foundation

/// Local Services (managed service profiles) UI strings.
enum ManagedServiceStrings {
    static let entries: [String: (en: String, zh: String)] = [
        // MARK: Validation and lifecycle errors
        "service.error.emptyName": (en: "Service name is required.", zh: "服务名称不能为空。"),
        "service.error.duplicateName": (en: "A service named “%@” already exists.", zh: "已存在名为“%@”的服务。"),
        "service.error.emptyHost": (en: "Host is required.", zh: "主机不能为空。"),
        "service.error.portRange": (en: "Port must be between 1 and 65535 (got %ld).", zh: "端口必须在 1 到 65535 之间（当前为 %ld）。"),
        "service.error.duplicatePort": (en: "Another service already uses port %ld.", zh: "另一个服务已使用端口 %ld。"),
        "service.error.missingDirectory": (en: "Working directory does not exist: %@", zh: "工作目录不存在：%@"),
        "service.error.emptyCommand": (en: "Start command is required.", zh: "启动命令不能为空。"),
        "service.error.unsupportedPlaceholder": (en: "Unsupported placeholder %@. Only {port} is allowed.", zh: "不支持的占位符 %@。仅允许使用 {port}。"),
        "service.error.launchFailed": (en: "Failed to launch the service command: %@", zh: "无法启动服务命令：%@"),
        "service.error.exitedBeforeReady": (en: "The process exited before port %ld became ready.", zh: "进程在端口 %ld 就绪前退出。"),
        "service.error.exitedUnexpectedly": (en: "The process exited unexpectedly (exit code %ld).", zh: "进程意外退出（退出码 %ld）。"),
        "service.error.startupTimeout": (en: "Port %ld did not become ready within %ld seconds.", zh: "端口 %ld 未在 %ld 秒内就绪。"),
        "service.error.stopFailed": (en: "Failed to stop the service.", zh: "无法停止服务。"),
        "service.error.portStillOccupied": (en: "Port %ld is still occupied after stopping.", zh: "停止后端口 %ld 仍被占用。"),
        "service.error.conflictStillOccupied": (en: "Port %ld is still occupied; the service was not started.", zh: "端口 %ld 仍被占用，服务未启动。"),
        "service.error.browserOpenFailed": (en: "Could not open %@ in the browser.", zh: "无法在浏览器中打开 %@。"),
        "service.error.tunnel": (en: "Quick Tunnel operation failed.", zh: "快速隧道操作失败。"),
        "service.error.invalidConfiguration": (en: "The service configuration is invalid.", zh: "服务配置无效。"),
        "service.error.notRunning": (en: "The service is not running.", zh: "服务未运行。"),
        "service.error.running": (en: "Stop the service first.", zh: "请先停止服务。"),
        "service.error.ownedRuntimeLost": (en: "The service process is no longer running.", zh: "服务进程已不再运行。"),
        "service.error.readinessLost": (en: "Port %ld stopped listening while the service was running.", zh: "服务运行期间端口 %ld 已停止监听。"),
        "service.error.conflictReplaced": (en: "Port %ld is now held by a different process; confirm again to terminate it.", zh: "端口 %ld 现由另一进程占用，请再次确认后再结束该进程。"),

        // MARK: Status
        "service.status.stopped": (en: "Stopped", zh: "已停止"),
        "service.status.starting": (en: "Starting", zh: "启动中"),
        "service.status.running": (en: "Running", zh: "运行中"),
        "service.status.stopping": (en: "Stopping", zh: "停止中"),
        "service.status.conflict": (en: "Conflict", zh: "冲突"),
        "service.status.failed": (en: "Failed", zh: "失败"),

        // MARK: Sidebar and list
        "service.title": (en: "Local Services", zh: "本地服务"),
        "service.add": (en: "Add Service", zh: "添加服务"),
        "service.addHelp": (en: "Add a local service", zh: "添加本地服务"),
        "service.searchPlaceholder": (en: "Search services...", zh: "搜索服务…"),
        "service.empty.title": (en: "No Services Yet", zh: "暂无服务"),
        "service.empty.detail": (en: "Add a local service to start and manage it from Port Manager.", zh: "添加本地服务，即可在 Port Manager 中启动和管理。"),
        "service.noSelection.title": (en: "No Service Selected", zh: "未选择服务"),
        "service.noSelection.detail": (en: "Select a service from the list to view details.", zh: "从列表中选择一个服务以查看详情。"),
        "service.count.total": (en: "%ld services", zh: "%ld 个服务"),
        "service.count.running": (en: "%ld running", zh: "%ld 个运行中"),
        "service.count.conflict": (en: "%ld conflicts", zh: "%ld 个冲突"),
        "service.badge.conflict": (en: "Conflict", zh: "冲突"),
        "service.badge.error": (en: "Error", zh: "错误"),

        // MARK: Actions
        "service.start": (en: "Start", zh: "启动"),
        "service.stop": (en: "Stop", zh: "停止"),
        "service.restart": (en: "Restart", zh: "重启"),
        "service.edit": (en: "Edit", zh: "编辑"),
        "service.delete": (en: "Delete", zh: "删除"),
        "service.open": (en: "Open", zh: "打开"),
        "service.cancel": (en: "Cancel", zh: "取消"),
        "service.save": (en: "Save", zh: "保存"),
        "service.action.starting": (en: "Starting...", zh: "启动中…"),
        "service.action.stopping": (en: "Stopping...", zh: "停止中…"),

        // MARK: Fields and editor
        "service.field.name": (en: "Name", zh: "名称"),
        "service.field.port": (en: "Port", zh: "端口"),
        "service.field.host": (en: "Host", zh: "主机"),
        "service.field.workingDirectory": (en: "Working Directory", zh: "工作目录"),
        "service.field.startCommand": (en: "Start Command", zh: "启动命令"),
        "service.field.chooseDirectory": (en: "Choose...", zh: "选择…"),
        "service.help.portPlaceholder": (en: "Use {port} to follow future port edits.", zh: "使用 {port} 以跟随后续端口修改。"),
        "service.help.foreground": (en: "Run the server in the foreground; daemonized commands are not supported.", zh: "请在前台运行服务，不支持守护进程化的命令。"),
        "service.help.secrets": (en: "Avoid embedding passwords or tokens; prefer environment variables.", zh: "请勿直接写入密码或令牌，建议使用环境变量。"),
        "service.editor.addTitle": (en: "Add Local Service", zh: "添加本地服务"),
        "service.editor.editTitle": (en: "Edit Local Service", zh: "编辑本地服务"),
        "service.editor.invalid": (en: "Fix the highlighted fields before saving.", zh: "请先修正错误后再保存。"),
        "service.editor.stopBeforeEdit": (en: "Stop the service before editing its configuration.", zh: "编辑配置前请先停止服务。"),
        "service.edit.confirmTitle": (en: "Stop Service to Edit?", zh: "要停止服务后再编辑吗？"),
        "service.edit.confirmMessage": (en: "“%@” is running. Editing requires stopping it first; it will not restart automatically after saving.", zh: "“%@”正在运行。编辑前需要先停止服务，保存后不会自动重启。"),
        "service.edit.stopAndEdit": (en: "Stop & Edit", zh: "停止并编辑"),
        "service.editor.validationFailed": (en: "The service configuration is invalid.", zh: "服务配置无效。"),

        // MARK: Detail
        "service.detail.workingDirectory": (en: "Working Directory", zh: "工作目录"),
        "service.detail.command": (en: "Start Command", zh: "启动命令"),
        "service.detail.rootPID": (en: "Root PID", zh: "主进程 PID"),
        "service.detail.listenerPIDs": (en: "Listener PIDs", zh: "监听进程 PID"),
        "service.detail.lastError": (en: "Last Error", zh: "最近错误"),
        "service.detail.output": (en: "Recent Output", zh: "最近输出"),
        "service.detail.startedAt": (en: "Started", zh: "启动时间"),
        "service.detail.exitCode": (en: "Exit Code", zh: "退出码"),
        "service.detail.noOutput": (en: "No output captured yet.", zh: "暂无输出。"),
        "service.log.copy": (en: "Copy", zh: "复制"),
        "service.log.clear": (en: "Clear", zh: "清空"),

        // MARK: Conflict
        "service.conflict.title": (en: "Port Conflict", zh: "端口冲突"),
        "service.conflict.message": (en: "Port %ld is already in use by another process.", zh: "端口 %ld 已被其他进程占用。"),
        "service.conflict.occupant": (en: "%@ (PID %ld) · %@", zh: "%@（PID %ld）· %@"),
        "service.conflict.pid": (en: "PID", zh: "PID"),
        "service.conflict.process": (en: "Process", zh: "进程"),
        "service.conflict.command": (en: "Command", zh: "命令"),
        "service.conflict.user": (en: "User", zh: "用户"),
        "service.conflict.address": (en: "Address", zh: "地址"),
        "service.conflict.killAndStart": (en: "Kill Occupying Process(es) & Start", zh: "结束占用进程并启动"),
        "service.conflict.cancel": (en: "Cancel", zh: "取消"),
        "service.conflict.startHelp": (en: "No process is killed without your confirmation.", zh: "未经确认不会结束任何进程。"),

        // MARK: Presets (picker, forms, field errors)
        "preset.custom.title": (en: "Custom Service", zh: "自定义服务"),
        "preset.picker.typeLabel": (en: "Type", zh: "类型"),
        "preset.advanced": (en: "Advanced Options", zh: "高级选项"),
        "preset.static-file-share.title": (en: "Static File Share", zh: "静态文件分享"),
        "preset.static-file-share.summary": (en: "Serve a directory over HTTP with Python.", zh: "用 Python 通过 HTTP 分享一个目录。"),
        "preset.static-file-share.field.directory": (en: "Directory", zh: "目录"),
        "preset.static-file-share.field.directory.help": (en: "The directory to share.", zh: "要分享的目录。"),
        "preset.ssh-local-forward.title": (en: "SSH Local Forward", zh: "SSH 本地转发"),
        "preset.ssh-local-forward.summary": (en: "Reach a remote port through an SSH host.", zh: "通过 SSH 主机访问远端端口。"),
        "preset.ssh-socks5-proxy.title": (en: "SSH SOCKS5 Proxy", zh: "SSH SOCKS5 代理"),
        "preset.ssh-socks5-proxy.summary": (en: "Route traffic through an SSH host as a SOCKS5 proxy.", zh: "将流量经由 SSH 主机以 SOCKS5 代理转发。"),
        "preset.dufs-file-share.title": (en: "Dufs File Share", zh: "Dufs 文件分享"),
        "preset.dufs-file-share.summary": (en: "Serve a directory with upload controls via Dufs.", zh: "用 Dufs 分享目录并可控制上传权限。"),
        "preset.dufs-file-share.field.directory": (en: "Directory", zh: "目录"),
        "preset.dufs-file-share.field.mode": (en: "Access Mode", zh: "访问模式"),
        "preset.dufs-file-share.field.mode.help": (en: "Controls upload and delete permissions.", zh: "控制上传与删除权限。"),
        "preset.dufs-file-share.mode.readOnly": (en: "Read only", zh: "只读"),
        "preset.dufs-file-share.mode.upload": (en: "Upload allowed", zh: "允许上传"),
        "preset.dufs-file-share.mode.readWrite": (en: "Read/write", zh: "可读写"),
        "preset.dufs-file-share.warning.noAuth": (en: "This share has no authentication: anyone on this Mac can reach it.", zh: "此分享没有鉴权：本机上的任何用户都可以访问。"),
        "preset.dufs-file-share.warning.writable": (en: "Writable shares let others modify the shared directory.", zh: "可写分享允许他人修改共享目录。"),
        "preset.jupyter-lab.title": (en: "Jupyter Lab", zh: "Jupyter Lab"),
        "preset.jupyter-lab.summary": (en: "Run a Jupyter Lab notebook server on a loopback port.", zh: "在回环端口上运行 Jupyter Lab 笔记本服务。"),
        "preset.jupyter-lab.field.directory": (en: "Notebook Directory", zh: "笔记目录"),
        "preset.jupyter-lab.field.directory.help": (en: "Root directory for notebooks.", zh: "笔记本的根目录。"),
        "preset.jupyter-lab.warning.token": (en: "Jupyter prints its access token to the service log; copy it from there.", zh: "Jupyter 会把访问令牌打印到服务日志中，请从日志复制。"),
        "preset.jupyter-lab.warning.public": (en: "The server binds to 127.0.0.1; sharing beyond this Mac needs a tunnel.", zh: "服务仅绑定 127.0.0.1；要让本机以外访问需要隧道。"),
        "preset.static-file-share.warning.listing": (en: "Anyone on this Mac can browse the shared directory.", zh: "本机上的任何用户都可以浏览该目录。"),
        "preset.static-file-share.warning.symlinks": (en: "Symlinks inside the directory are followed.", zh: "目录中的符号链接会被跟随。"),
        "preset.file-share.warning.homeRoot": (en: "Sharing your home directory exposes everything in it. Consider choosing a narrower folder.", zh: "分享主目录会暴露其中全部内容。建议选择更具体的目录。"),
        "preset.ssh.field.host": (en: "SSH Host", zh: "SSH 主机"),
        "preset.ssh.field.host.help": (en: "Alias from ~/.ssh/config or user@host.", zh: "~/.ssh/config 中的别名或 user@host。"),
        "preset.ssh.field.remoteHost": (en: "Remote Host", zh: "远端主机"),
        "preset.ssh.field.remoteHost.help": (en: "Host as seen from the SSH server.", zh: "从 SSH 服务器看的远端主机。"),
        "preset.ssh.field.remotePort": (en: "Remote Port", zh: "远端端口"),
        "preset.ssh.field.keepaliveInterval": (en: "Keepalive Interval (s)", zh: "保活间隔（秒）"),
        "preset.ssh.field.keepaliveInterval.help": (en: "ServerAliveInterval for the connection.", zh: "连接的 ServerAliveInterval。"),
        "preset.ssh.field.keepaliveCount": (en: "Keepalive Count", zh: "保活次数"),
        "preset.error.empty": (en: "%@ is required.", zh: "必须填写%@。"),
        "preset.error.notAnInteger": (en: "%@ must be a number.", zh: "%@ 必须是数字。"),
        "preset.error.invalidCharacters": (en: "%@ contains characters that are not allowed here.", zh: "%@ 包含此处不允许的字符。"),
        "preset.error.outOfRange": (en: "Enter a value in the valid range.", zh: "请输入有效范围内的值。"),
        "preset.error.rootDirectory": (en: "The root directory cannot be shared.", zh: "根目录不能作为分享目录。"),

        // MARK: Dependency discovery (preset forms)
        "dependency.notInstalled": (en: "Not installed", zh: "未安装"),
        "dependency.availableTitle": (en: "Dependency Ready", zh: "依赖就绪"),
        "dependency.available": (en: "Installed at %@.", zh: "已安装于 %@。"),
        "dependency.notInstalledTitle": (en: "%@ is not installed", zh: "未安装 %@"),
        "dependency.ssh.notInstalled": (en: "The OpenSSH client ships with macOS; reinstall the system or run softwareupdate.", zh: "OpenSSH 客户端随 macOS 提供；请重装系统或运行 softwareupdate。"),
        "dependency.python3.notInstalled": (en: "Install Python 3 via python.org or Homebrew.", zh: "请通过 python.org 或 Homebrew 安装 Python 3。"),
        "dependency.python3.stub": (en: "The Command Line Tools stub is present but not set up; run xcode-select --install or install Python directly.", zh: "检测到命令行工具的占位程序，但尚未安装；请运行 xcode-select --install 或直接安装 Python。"),
        "dependency.dufs.notInstalled": (en: "Install Dufs via Homebrew (brew install dufs) or download it from GitHub.", zh: "请通过 Homebrew（brew install dufs）安装 Dufs，或从 GitHub 下载。"),
        "dependency.jupyter.notInstalled": (en: "Install Jupyter with pip (pip install jupyterlab).", zh: "请使用 pip 安装 Jupyter（pip install jupyterlab）。"),
        "dependency.viewInstallDocs": (en: "View installation docs…", zh: "查看安装文档…"),

        // MARK: Delete
        "service.delete.title": (en: "Delete Service", zh: "删除服务"),
        "service.delete.stoppedMessage": (en: "Delete service “%@”? This removes the saved configuration.", zh: "删除服务“%@”？这将移除已保存的配置。"),
        "service.delete.stopAndDeleteMessage": (en: "Stop and delete “%@”? The owned service will be stopped first.", zh: "停止并删除“%@”？将先停止该本应用管理的服务。"),
        "service.delete.stopAndDeleteTunnelMessage": (en: "Stop and delete “%@”? The owned service and its temporary public tunnel will both be stopped.", zh: "停止并删除“%@”？该服务及其临时公网隧道都将被停止。"),
        "service.delete.conflictMessage": (en: "Delete configuration “%@”? The external process using port %ld will not be terminated.", zh: "删除配置“%@”？不会终止占用端口 %ld 的外部进程。"),
        "service.delete.stopAndDeleteButton": (en: "Stop & Delete", zh: "停止并删除"),
        "service.delete.deleteConfigurationButton": (en: "Delete Configuration Only", zh: "仅删除配置"),
        "service.delete.confirm": (en: "Delete", zh: "删除"),

        // MARK: Quick Tunnel
        "service.tunnel.start": (en: "Start Tunnel", zh: "启动隧道"),
        "service.tunnel.starting": (en: "Starting tunnel...", zh: "正在启动隧道…"),
        "service.tunnel.publicURL": (en: "Public URL", zh: "公网地址"),
        "service.tunnel.copy": (en: "Copy", zh: "复制"),
        "service.tunnel.open": (en: "Open", zh: "打开"),
        "service.tunnel.stop": (en: "Stop Tunnel", zh: "停止隧道"),
        "service.tunnel.retry": (en: "Retry", zh: "重试"),
        "service.tunnel.unavailable": (en: "cloudflared is not installed. Install it to share this service.", zh: "未安装 cloudflared。安装后即可分享此服务。"),
        "service.tunnel.stopped": (en: "No tunnel running.", zh: "隧道未运行。"),

        // Network Access grouping (design section 7.2): intent-based labels over
        // the unchanged Quick Tunnel runtime.
        "service.exposure.title": (en: "Network Access", zh: "网络访问"),
        "service.exposure.local": (en: "Local", zh: "本机"),
        "service.exposure.localIdle": (en: "Start the service to access it locally.", zh: "启动服务后即可在本机访问。"),
        "service.exposure.temporaryPublic": (en: "Temporary public", zh: "临时公网"),
        "service.exposure.temporaryPublicHelper": (en: "Uses a Cloudflare Quick Tunnel. The address is random and disappears when the tunnel or Port Manager stops.", zh: "通过 Cloudflare Quick Tunnel 提供。地址随机，隧道或 Port Manager 停止后即失效。"),
        "service.exposure.stablePublic": (en: "Cloudflare Named Tunnel — configure or view in Tunnels", zh: "Cloudflare 命名隧道——前往 Tunnels 配置或查看"),
        "exposure.confirm.title": (en: "Share this service publicly?", zh: "公开分享该服务？"),
        "exposure.confirm.start": (en: "Share", zh: "分享"),
        "exposure.warning.dufsWritablePublic": (en: "This share is writable and has no authentication. Sharing it publicly lets anyone upload, modify or delete files in the shared directory.", zh: "该分享可写且无身份验证。公开分享后任何人都可以上传、修改或删除共享目录中的文件。"),
        "exposure.warning.dufsPublic": (en: "This share has no authentication. Sharing it publicly lets anyone read the shared directory.", zh: "该分享无身份验证。公开分享后任何人都可以读取共享目录。"),
        "exposure.warning.jupyterPublic": (en: "Sharing Jupyter publicly lets anyone run code on this Mac through the notebook interface.", zh: "公开分享 Jupyter 后，任何人都可以通过笔记本界面在这台 Mac 上运行代码。"),
    ]
}
