import Foundation

/// Port list, detail panel, sidebar, context menus and empty states.
enum PortStrings {
    static let entries: [String: (en: String, zh: String)] = [
        "ports.searchPlaceholder": (en: "Search ports, processes...", zh: "搜索端口、进程…"),
        "ports.killAllTitle": (en: "Kill All Processes", zh: "结束全部进程"),
        "ports.killAllCount": (en: "Kill All (%ld processes)", zh: "结束全部（%ld 个进程）"),
        "ports.killAllConfirm": (en: "Are you sure you want to kill all %ld processes? This action cannot be undone.", zh: "确定要结束全部 %ld 个进程吗？此操作无法撤销。"),
        "ports.noSelectionTitle": (en: "No Port Selected", zh: "未选择端口"),
        "ports.noSelectionDetail": (en: "Select a port from the list to view details", zh: "从列表中选择一个端口以查看详情"),
        "ports.filteredCount": (en: "%ld of %ld ports", zh: "%ld / %ld 个端口"),
        "ports.listeningCount": (en: "%ld ports listening", zh: "%ld 个端口正在监听"),
        "ports.scanning": (en: "Scanning...", zh: "正在扫描…"),
        "ports.refreshHelp": (en: "Refresh port list (Cmd+R)", zh: "刷新端口列表（Cmd+R）"),
        "ports.section.categories": (en: "Categories", zh: "分类"),
        "ports.section.networking": (en: "Networking", zh: "网络"),
        "ports.section.processTypes": (en: "Process Types", zh: "进程类型"),
        "ports.section.filters": (en: "Filters", zh: "筛选"),
        "ports.allPorts": (en: "All Ports", zh: "全部端口"),
        "ports.favorites": (en: "Favorites", zh: "收藏"),
        "ports.favorite": (en: "Favorite", zh: "收藏"),
        "ports.watched": (en: "Watched", zh: "监听"),
        "ports.watching": (en: "Watching", zh: "监听中"),
        "ports.addFavoriteHelp": (en: "Add Favorite Port", zh: "添加收藏端口"),
        "ports.addWatchedHelp": (en: "Add Watched Port", zh: "添加监听端口"),
        "ports.addPort": (en: "Add Port...", zh: "添加端口…"),
        "ports.addPortField": (en: "Port (1-65535)", zh: "端口（1-65535）"),
        "ports.notifyOnStart": (en: "Notify when port starts", zh: "端口启动时通知"),
        "ports.notifyOnStop": (en: "Notify when port stops", zh: "端口停止时通知"),
        "ports.k8sPortForward": (en: "K8s Port Forward", zh: "K8s 端口转发"),
        "ports.portRange": (en: "Port Range", zh: "端口范围"),
        "ports.min": (en: "Min", zh: "最小"),
        "ports.max": (en: "Max", zh: "最大"),
        "ports.resetFilters": (en: "Reset Filters", zh: "重置筛选"),
        "ports.notes": (en: "Notes", zh: "备注"),
        "ports.addNotePrompt": (en: "Add a note for port %ld…", zh: "为端口 %ld 添加备注…"),
        "ports.noteTitle": (en: "Note for Port %ld", zh: "端口 %ld 的备注"),
        "ports.notePrompt": (en: "Add freeform notes about this port.", zh: "为此端口添加自由备注。"),
        "ports.labelTitle": (en: "Set Label for Port %ld", zh: "设置端口 %ld 的标签"),
        "ports.labelPrompt": (en: "Enter a custom name to identify this port.", zh: "输入自定义名称以标识此端口。"),
        "ports.kill": (en: "Kill", zh: "结束"),
        "ports.killProcess": (en: "Kill Process", zh: "结束进程"),
        "ports.killProcessHelp": (en: "Kill process", zh: "结束进程"),
        "ports.killProcessTree": (en: "Kill Process Tree", zh: "结束进程树"),
        "ports.forceKill": (en: "Force Kill (SIGKILL)", zh: "强制结束（SIGKILL）"),
        "ports.deepKill": (en: "Deep Kill (+ Connections)", zh: "深度结束（含连接）"),
        "ports.killConfirm": (en: "Kill %@?", zh: "结束 %@？"),
        "ports.killConfirmDetail": (en: "Are you sure you want to kill %@ on port %ld?", zh: "确定要结束 %@ 吗？它正在监听端口 %ld。"),
        "ports.portNumber": (en: "Port %ld", zh: "端口 %ld"),
        "ports.pid": (en: "PID %ld", zh: "PID %ld"),
        "ports.exposedViaTunnel": (en: "Exposed via Cloudflare Tunnel", zh: "已通过 Cloudflare 隧道公开"),
        "ports.command": (en: "Command", zh: "命令"),
        "ports.copyCommand": (en: "Copy Command", zh: "复制命令"),
        "ports.copyPortNumber": (en: "Copy Port Number", zh: "复制端口号"),
        "ports.copyURLOf": (en: "Copy %@", zh: "复制 %@"),
        "ports.removeLabel": (en: "Remove Label", zh: "移除标签"),
        "ports.removeNote": (en: "Remove Note", zh: "移除备注"),
        "ports.resetToAuto": (en: "Reset to Auto", zh: "重置为自动"),
        "ports.setProcessType": (en: "Set Process Type", zh: "设置进程类型"),
        "ports.noPorts": (en: "No Ports", zh: "未发现端口"),
        "ports.noListeningPorts": (en: "No listening ports found", zh: "未发现正在监听的端口"),
        "ports.column.process": (en: "Process", zh: "进程"),
        "ports.column.port": (en: "Port", zh: "端口"),
        "ports.removeFromList": (en: "Remove from list", zh: "从列表中移除"),
        "ports.toggleFavoriteHelp": (en: "Toggle favorite", zh: "切换收藏"),
        "ports.toggleWatchHelp": (en: "Toggle watch", zh: "切换监听"),
        "ports.inactive": (en: "Inactive", zh: "未激活"),
        "ports.portCount": (en: "%ld port(s)", zh: "%ld 个端口"),
        "ports.processType.webServer": (en: "Web Server", zh: "Web 服务器"),
        "ports.processType.database": (en: "Database", zh: "数据库"),
        "ports.processType.development": (en: "Development", zh: "开发"),
        "ports.processType.system": (en: "System", zh: "系统"),
        "ports.processType.other": (en: "Other", zh: "其他"),
        "ports.addToFavorites": (en: "Add to Favorites", zh: "添加收藏"),
        "ports.removeFromFavorites": (en: "Remove from Favorites", zh: "取消收藏"),
        "ports.addFavorite": (en: "Add Favorite", zh: "添加收藏"),
        "ports.removeFavorite": (en: "Remove Favorite", zh: "取消收藏"),
        "ports.watch": (en: "Watch", zh: "监听"),
        "ports.watchPort": (en: "Watch Port", zh: "监听端口"),
        "ports.stopWatching": (en: "Stop Watching", zh: "停止监听"),
        "ports.setLabel": (en: "Set Label", zh: "设置标签"),
        "ports.editLabel": (en: "Edit Label", zh: "编辑标签"),
        "ports.addNote": (en: "Add Note", zh: "添加备注"),
        "ports.editNote": (en: "Edit Note", zh: "编辑备注"),
        "ports.labelPlaceholder": (en: "e.g., Frontend Dev Server", zh: "例如：前端开发服务器"),
        "ports.detailLabel": (en: "Label", zh: "标签"),
        "ports.detailPid": (en: "PID", zh: "PID"),
        "ports.detailAddress": (en: "Address", zh: "地址"),
        "ports.detailUser": (en: "User", zh: "用户"),
        "ports.detailFd": (en: "File Descriptor", zh: "文件描述符"),
        "ports.detailType": (en: "Type", zh: "类型"),
        "ports.addFavoriteTitle": (en: "Add Favorite Port", zh: "添加收藏端口"),
        "ports.addWatchedTitle": (en: "Add Watched Port", zh: "添加监听端口"),
        "ports.listView": (en: "List View", zh: "列表视图"),
        "ports.treeView": (en: "Tree View", zh: "树状视图"),
        "ports.switchToListView": (en: "Switch to List View", zh: "切换到列表视图"),
        "ports.switchToTreeView": (en: "Switch to Tree View", zh: "切换到树状视图"),
        "ports.notRunning": (en: "Not running", zh: "未运行"),
    ]
}
