using PortKiller.Models;
namespace PortKiller.Services;
public sealed class ManagedServiceManager
{
 public const int MaxOutputLines=200; public static readonly TimeSpan ReadinessTimeout=TimeSpan.FromSeconds(20); public static readonly TimeSpan ReadinessPollInterval=TimeSpan.FromMilliseconds(250); public static readonly TimeSpan StopTimeout=TimeSpan.FromSeconds(5);
 private readonly IManagedServiceStorage _storage; private readonly IManagedServiceProcessController _processes; private readonly IManagedServicePortInspector _ports; private readonly Dictionary<Guid,ManagedServiceState> _states=new(); private readonly object _gate=new();
 public ManagedServiceManager(IManagedServiceStorage storage,IManagedServiceProcessController processes,IManagedServicePortInspector ports){_storage=storage;_processes=processes;_ports=ports;_processes.Output+=OnOutput;}
 public IReadOnlyList<ManagedServiceState> Load(){lock(_gate){_states.Clear();foreach(var c in _storage.Load())_states[c.Id]=new ManagedServiceState(c);return _states.Values.ToList();}}
 public ManagedServiceState Add(ManagedServiceConfig c){c=c.Clone();if(c.Id==Guid.Empty)c.Id=Guid.NewGuid();var error=ManagedServiceValidator.Validate(c,Configs());if(error!=null)throw new ArgumentException(error.Message);var s=new ManagedServiceState(c);lock(_gate)_states[c.Id]=s;Persist();return s;}
 public bool Remove(Guid id){if(!_states.TryGetValue(id,out var s)||s.IsRunning)return false;lock(_gate)_states.Remove(id);Persist();return true;}
 public bool Update(Guid id,ManagedServiceConfig c){if(!_states.TryGetValue(id,out var s)||s.IsRunning)return false;c=c.Clone();c.Id=id;var error=ManagedServiceValidator.Validate(c,Configs());if(error!=null)throw new ArgumentException(error.Message);s.Config=c;Persist();return true;}
 public async Task<bool> StartAsync(Guid id,CancellationToken ct=default){if(!_states.TryGetValue(id,out var s)||s.IsTransitioning||s.IsRunning)return false;var occupants=await _ports.InspectAsync(s.Config.Port,ct);if(occupants.Count>0){s.Conflict=new ManagedServiceConflict{ServiceId=id,Port=s.Config.Port,Occupants=occupants.Select(x=>new ManagedServiceOccupant{Pid=x.Pid,ProcessName=x.ProcessName,User=x.User,Command=x.Command,Address=x.Address}).ToList()};s.Status=ManagedServiceStatus.Conflict;return false;}s.Status=ManagedServiceStatus.Starting;s.LastError=null;try{s.RootPid=await _processes.StartAsync(s.Config,ct);var until=DateTime.UtcNow+ReadinessTimeout;while(DateTime.UtcNow<until){ct.ThrowIfCancellationRequested();if(await _ports.IsReadyAsync(s.Config.Port,ct)){s.Status=ManagedServiceStatus.Running;s.StartedAt=DateTime.Now;return true;}await Task.Delay(ReadinessPollInterval,ct);}s.LastError="Service did not listen on configured port.";await StopAsync(id,CancellationToken.None);s.Status=ManagedServiceStatus.Failed;return false;}catch(Exception ex){s.LastError=ex.Message;s.Status=ManagedServiceStatus.Failed;return false;}}
 public async Task<bool> StopAsync(Guid id,CancellationToken ct=default){if(!_states.TryGetValue(id,out var s))return false;if(!s.IsOwned){s.Status=ManagedServiceStatus.Stopped;return true;}s.Status=ManagedServiceStatus.Stopping;using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(StopTimeout);try{await _processes.StopAsync(s.RootPid!.Value,timeout.Token);}catch(OperationCanceledException){s.LastError="Timed out stopping service.";return false;}s.ClearRuntime();s.Status=ManagedServiceStatus.Stopped;return true;}
 public async Task<bool> RestartAsync(Guid id,CancellationToken ct=default){if(!await StopAsync(id,ct))return false;return await StartAsync(id,ct);}
 public bool ResolveConflict(Guid id,IEnumerable<int> confirmedPids){if(!_states.TryGetValue(id,out var s)||s.Status!=ManagedServiceStatus.Conflict)return false;s.ListenerPids.Clear();foreach(var pid in confirmedPids.Distinct())s.ListenerPids.Add(pid);s.Conflict=null;s.Status=ManagedServiceStatus.Stopped;return true;}
 public Task<bool> StopForEditAsync(Guid id,CancellationToken ct=default)=>StopAsync(id,ct);
 private IReadOnlyList<ManagedServiceConfig> Configs()=>_states.Values.Select(x=>x.Config).ToList(); private void Persist()=>_storage.Save(Configs()); private void OnOutput(object? sender,ManagedServiceOutputEventArgs e){if(_states.TryGetValue(e.ServiceId,out var s))s.AppendOutput(e.Text,e.Stream);}
}
